timeout: 100000
enableRobotsTXT: true
languageCode: en-US
params:
  description: Fast, simple & clean blog theme for Hugo.
  favicon:
    ico: ""
    png: ""
    svg: ""
  image: ""
  logo:
    header: ""
    footer: ""
  staticFormsAccessKey: ""
markup:
  highlight:
    style: nord
permalinks:
  post: /:year/:month/:day/:slug/
rssLimit: 100
module:
  imports:
    - path: github.com/datakrama/nyerat-hugo-theme
minify:
  tdewolff:
    html:
      keepQuotes: true
      keepWhitespace: false
summaryLength: 25
taxonomies:
  category: category
  tag: tags
  author: authors
title: Nyerat Starter
baseURL: /
sectionPagesMenu: main
paginate: 8
